#version: "3.9"
services:
  db:
    image: byskymars/gymtrack-db:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    image: byskymars/gymtrack-web:latest
    command: tail -f /dev/null 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres

  metabase:
    image: byskymars/gymtrack-metabase:latest
    container_name: metabase
    volumes:
      - metabase_data:/metabase-data

    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: password
      MB_DB_HOST: db
    depends_on:
      - db

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@gymtrack.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
  dbgate:
    image: dbgate/dbgate
    ports:
      - "3030:3000"
volumes:
  db_data:
  metabase_data:
